language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# - "3.7"  # TODO: Re-enable after https://github.com/travis-ci/travis-ci/issues/9815 is fixed

sudo: false
install:
  - pip install tox-travis coveralls
script:
  - tox
after_success:
    - coveralls

#install:
#  - pip install pipenv
#  - pipenv install --dev
#script:
#  - pipenv run pytest tests/
